var locators={

    fNameSel: '#mat-input-1',
    lNameSel:'#mat-input-2',
    address:'#mat-input-3',
    app:'#mat-input-4',
    addCode:'#mat-input-5',
    num:'#mat-input-6',
    email:'#mat-input-0',
    password:'#mat-input-1',
    login:':nth-child(4) > .full-width > .mat-button-wrapper',
    forgetlink:'form.ng-untouched > div.custom-vertical-spacer > a',
    errormessage:'.toast-title',
    ref:'#mat-input-8',
    userdemo:'.dropdown-toggle',
    navigation:'#app-navbar-collapse',
    viewform:':nth-child(1) > .panel > .bold > .panel-footer > .pull-left',
    createform:':nth-child(2) > .panel > .color-dark > .panel-footer > .pull-left',
    viewusrrole:':nth-child(3) > .panel > .bold > .panel-footer > .pull-left',
    userlist:':nth-child(4) > .panel > .bold > .panel-footer > .pull-left',
    forgetpswd:'#mat-input-2',
    logout:'.dropdown-menu > :nth-child(2) > a',
    successtoast:'.toast-title',
    sendemail:'.mat-button-wrapper',
    formmanage:'[fxlayoutalign="start"]',
    backbutton:'.back-btn',
    formbuilder:'[routerlink="/qforms/form-builder/0"] > div',
    createnewuser:'#button_add_user',
    rolelist:'[fxflex="20"]',
    newrole:'#button_add_user',
    userlistlabel:'[fxflex="40"]',
    billing:':nth-child(5) > .panel > .panel-heading',
    clientid:'.mat-sort-header-button',
    textcreateform:'h3',
    text2createform:'h4',
    uploadpf:'[fxlayout="row"] > :nth-child(2) > div',
    dragyouroption:'.font-16',
    plusicon:'.toggle-entry-add > .mat-button-wrapper > .material-icons',
    control:'#mat-tab-label-0-0 > .mat-tab-label-content',
    typography:'#headingTypography > .panel-title > a',
    heading:'#header > .col-md-10',
    paragraph:'#typoparagraph > .col-md-10',
    canvas:'.page-container-warapper',
    imagetext:'#imagelefttext > .col-md-10' ,
    errorunreg:'.toast-title',
    toastmsg:'.toast-message'
   
   
}
export {locators}